### ISSUE TITLE
What is this device?

### ISSUE THREAD

**Issue by jackinloadup** [mrVanDalo/nixos-config#1]
Great configs! I'll be referencing this quite a bit. 

May I ask what is the /dev/store device? What driver is running this dev? I couldn't quite figure it out by scanning your configs.

https://github.com/mrVanDalo/nixos-config/blob/7656ea428be521e24d9402ee4e28028ee38d3c8c/filesystem.nix#L59

Thanks again for the gold mine!

**Comment by mrVanDalo** [comment]
hey @jackinloadup this repository is quite old. I'm using my private [git server](https://git.ingolf-wagner.de/palo/nixos-config) for now. But this will change soon too.
`/dev/store` as well as `/dev/vg` are lvm volume groups. 
* `/dev/vg` is my ssd which holds `/`, `/home` and similar folders. 
* `/dev/store` is usually an hdd which old movies, music, ... nowadays I encrypt every folder in `/dev/store` with a key which is placed in `/root/keys` so during boot everything is being decrypted using only one password.

**Comment by jackinloadup** [comment]
Interesting, I haven't played with lvm a ton so I wasn't aware you could specify devices outside of `/dev/mapper`. I'll have to look into this more.

Is the idea with multiple keys per folder in `/dev/store` to allow access to only a single folder for certain parties? Say a media player has a key to movies and music? Or maybe for a multi-boot setup where say nix has access to all but an Ubuntu install has access to music.

Just curious about your underlying motivation as I'm planning my own overhaul.

I'll checkout your private repo.

Thank @mrVanDalo

**Comment by mrVanDalo** [comment]
> Is the idea with multiple keys per folder in `/dev/store` to allow access to only a single folder for certain parties? Say a media player has a key to movies and music? Or maybe for a multi-boot setup where say nix has access to all but an Ubuntu install has access to music.

The idea was to have big folders in my file tree. I always encrypt my file systems. Also I only wanted to type in the LUKS only once.
So I type in my luks password => decrypt `/` (inkluding `/root/keys`) and now I can mount all other partitions (which are encrypted with files laying in `/root/keys`)
It's a bit complicated I have to admit.
